server: 
    port: 9111
spring:
    application:
        name: feign-server-avro
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false

logging:
    level:
        root: info
    
#management:
#    endpoints:
#        web:
#            exposure:
#                include: all
#        health:
#            show-details: always
            
